{% set name = "fastapi-users" %}
{% set version = "10.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ab9dd218db088bc2d04474ec5fd0040971cea027186041d6d33979f990917d9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-regex-commit
    - pip
    - python >=3.7
  run:
    - email-validator >=1.1.0,<1.4
    - fastapi >=0.65.2,<0.76.0
    - makefun >=1.11.2,<2.0.0
    - passlib ==1.7.4
    - pyjwt ==2.6.0
    - python >=3.7
    - python-multipart ==0.0.5
    - typing-extensions >=4.1.1

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
