{% set name = "fastapi-users" %}
{% set version = "9.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-users-{{ version }}.tar.gz
  sha256: 543e8bf98e5415a5b96fb5e73c2f389472c7b2f1475cf94dbb1c4e627b31a663

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - email-validator >=1.1.0,<1.2
    - fastapi >=0.65.2,<0.69.0
    - makefun >=1.9.2,<1.12
    - passlib ==1.7.4
    - pydantic
    - pyjwt ==2.3.0
    - python >=3.7
    - python-multipart ==0.0.5

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
