{% set name = "fastapi-users" %}
{% set version = "10.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-users-{{ version }}.tar.gz
  sha256: f56dc687d99ea3574462d2e67596da5200695ed3a3eded2acd9f043b80feb534

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - email-validator >=1.1.0,<1.2
    - fastapi >=0.65.2,<0.76.0
    - makefun >=1.11.2,<1.14
    - passlib ==1.7.4
    - pydantic
    - pyjwt ==2.4.0
    - python >=3.7
    - python-multipart ==0.0.5
    - typing-extensions >=4.1.1

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
