{% set name = "fastapi-users" %}
{% set version = "10.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi-users-{{ version }}.tar.gz
  sha256: 47cb99eef18eea654170674f5a86c4bed898a6ee666b45007f9805e687ff32f5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.7
  run:
    - email-validator >=1.1.0,<1.2
    - fastapi >=0.65.2,<0.76.0
    - makefun >=1.11.2,<2.0.0
    - passlib ==1.7.4
    - pydantic
    - pyjwt ==2.4.0
    - python >=3.7
    - python-multipart ==0.0.5
    - typing-extensions >=4.1.1

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
