{% set name = "fastapi-users" %}
{% set version = "10.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 875d43e9c65902f652b939c9d4c95dbb586f01417cfee355ad47989d4dc44cf3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-regex-commit
    - pip
    - python >=3.7
  run:
    # For passlib[bcrypt]
    - bcrypt >=3.1.0
    # For pyjwt[crypto]
    - cryptography >=3.4.0
    - email-validator >=1.1.0,<1.4
    - fastapi >=0.65.2
    - makefun >=1.11.2,<2.0.0
    - passlib ==1.7.4
    - pyjwt ==2.6.0
    - python >=3.7
    - python-multipart ==0.0.6
    - typing-extensions >=4.1.1

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
