{% set name = "fastapi-users" %}
{% set version = "14.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6dceefbd2db87a17f791ef431d616bb5ce40cb123da7922969b704cbee5e7384

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-regex-commit
    - pip
    - python >=3.8
  run:
    - email-validator >=1.1.0,<2.2
    - fastapi >=0.65.2
    - makefun >=1.11.2,<2.0.0
    - pyjwt ==2.8.0
    - python >=3.8
    - python-multipart ==0.0.9
    - pwdlib ==0.2.0

    # For pwdlib[argon2, bcrypt]
    - bcrypt ==4.1.2
    - argon2-cffi ==23.1.0

    # For pyjwt[crypto]
    - cryptography >=3.4.0

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
