{% set name = "fastapi-users" %}
{% set version = "12.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9a9b44e0917c483aaba2bf80ea488b4ba6475b0fb24e2abfaf21e0b5c5db59bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - hatch-regex-commit
    - pip
    - python >=3.8
  run:
    - email-validator >=1.1.0,<2.1
    - fastapi >=0.65.2
    - makefun >=1.11.2,<2.0.0
    - passlib ==1.7.4
    - pyjwt ==2.7.0
    - python >=3.8
    - python-multipart ==0.0.6

    # For passlib[bcrypt]
    - bcrypt >=3.1.0

    # For pyjwt[crypto]
    - cryptography >=3.4.0

test:
  imports:
    - fastapi_users
    - fastapi_users.authentication
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fastapi-users/fastapi-users
  summary: Ready-to-use and customizable users management for FastAPI.
  doc_url: https://fastapi-users.github.io/fastapi-users/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - davidbrochart
